id = "kpl"
name = "KPL"
version = "0.0.1"
schema_version = 1
authors = ["Cwooper <cwooperm@gmail.com>"]
description = "KPL (Kernel Programming Language) support for Zed"
repository = "https://github.com/Cwooper/zed-kpl"

[grammars.kpl]
repository = "https://github.com/Cwooper/tree-sitter-kpl"
rev = "5a853c23cdbc909f402c8da6b7f516d645a53c02"
