id = "kpl"
name = "KPL"
version = "0.0.1"
schema_version = 1
authors = ["Cwooper <cwooperm@gmail.com>"]
description = "KPL (Kernel Programming Language) support for Zed"
repository = "https://github.com/Cwooper/zed-kpl"

[grammars.kpl]
repository = "https://github.com/Cwooper/tree-sitter-kpl"
rev = "8d10dfa4917ae7e40c81d80433dbbcc395e9e04f"
